#!/usr/bin/env python3
"""Validate real GitHub Actions workflow files against workflow.osd,
and show the resulting OML.

For each fixture: read the YAML, validate it against the schema, and
either print the equivalent OML or the exact validation error. Unlike
the pyproject.toml and package.json examples, this one also
demonstrates a **read failure**, not just a validation failure: three
of the four fixtures are real GitHub Actions workflows using the
ordinary, unquoted ``on:`` key, and PyYAML's YAML 1.1 boolean-coercion
rule turns that bare key into the Python boolean ``True`` -- which
omnist's Document model rejects, since labels must be strings. This is
caught and reported explicitly, never left as an uncaught exception.
See docs/examples/github-actions.md for the full explanation.

Each fixture that *does* read successfully has its OML committed
alongside it as ``<name>.oml``, generated by this same ``write_oml``
call. ``tests/test_examples_github_actions.py`` recomputes it and
asserts an exact match.

Run: python3 examples/github-actions/convert.py
"""
from pathlib import Path

from omnist import Doc, DocumentError, ParseError, parse_schema, read_yaml, write_oml

HERE = Path(__file__).parent
FIXTURES = sorted((HERE / "fixtures").glob("*.yml"))


def main():
    schema = parse_schema((HERE / "workflow.osd").read_text())

    for fixture in FIXTURES:
        print(f"== {fixture.name} ==")
        try:
            node = read_yaml(fixture.read_text(), schema=schema)
        except (DocumentError, ParseError) as exc:
            print("read: False")
            print(f"  {type(exc).__name__}: {exc}")
            print()
            continue
        result = schema.validate(Doc(node))
        print("read: True")
        if result.ok:
            print("valid: True")
            print(write_oml(node))
        else:
            print("valid: False")
            print(result)
        print()


if __name__ == "__main__":
    main()
