#!/usr/bin/env python3
"""Validate real package.json files against package.osd, and show the
resulting OML.

For each fixture: read the JSON, validate it against the schema, and
either print the equivalent OML or the exact validation error -- never
an uncaught exception. Also a stress test of ``read_json``/``write_oml``
against real-world package.json shapes, independent of whether the
schema itself is a good fit.

Each fixture's OML is also committed alongside it as ``<name>.oml`` --
generated by this same ``write_oml`` call, not hand-written.
``tests/test_examples_package_json.py`` recomputes it and asserts an
exact match, so a committed file can't silently drift from what running
this script actually produces.

``read_json`` is called with ``schema=`` -- the idiomatic call when the
schema is already in hand, upgrading value-exact leaves (ISO strings to
real ``date``/``time``/``datetime``, ints to ``number``) to match the
schema. It's a no-op here: ``package.osd`` has no ``date``/``time``/
``datetime``/``number`` field, only ``string``, ``boolean``, ``any``,
and ``Ref`` -- see docs/examples/package-json.md for why.

Run: python3 examples/package-json/convert.py
"""
from pathlib import Path

from omnist import Doc, parse_schema, read_json, write_oml

HERE = Path(__file__).parent
FIXTURES = sorted((HERE / "fixtures").glob("*.json"))


def main():
    schema = parse_schema((HERE / "package.osd").read_text())

    for fixture in FIXTURES:
        print(f"== {fixture.name} ==")
        node = read_json(fixture.read_text(), schema=schema)
        result = schema.validate(Doc(node))
        if result.ok:
            print("valid: True")
            print(write_oml(node))
        else:
            print("valid: False")
            print(result)
        print()


if __name__ == "__main__":
    main()
